### ISSUE TITLE
unable to run code in VS 2017

### ISSUE THREAD

**Issue by billwoo** [davidwest/TreeCollections#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0115	'AdvancedMutableCategoryNode.Create(DualStateCategoryItem, AdvancedMutableCategoryNode)': no suitable method found to override	DemoConsole45	C:\Users\test_user\Desktop\TreeCollections-master\TreeCollections-master\TreeCollections\DemoConsole45\Demos\Classes\ClassesForAdvanced.cs	73	Active

44 errors trying to run the DemoConosole45 

Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1004	Assets file 'C:\Users\test_user\Desktop\TreeCollections-master\TreeCollections-master\TreeCollections\src\DemoConsole\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.	DemoConsole	C:\Program Files\dotnet\sdk\2.1.505\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	198	

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'DualStateEntityDefinition<,,>' could not be found (are you missing a using directive or an assembly reference?)	DemoConsole45	C:\Users\test_user\Desktop\TreeCollections-master\TreeCollections-master\TreeCollections\DemoConsole45\Demos\Classes\ClassesForAdvanced.cs	7	Active

**Comment by davidwest** [comment]
Resolved
